function names = turnFeatureNames()
%TURNFEATURENAMES Names of the turnFeatures vector, in order.
%   e = r - Vx*tan(delta)/L, q = ay - Vx*r. bp* = log10 band power, *_lo..*_hi bands in Hz.

names = {'Vturn', ...
    'bpE_0.2-0.6', 'bpE_0.6-1.0', 'bpE_1.0-1.5', 'bpE_1.5-2.0', 'bpE_2.0-3.0', ...
    'bpQ_0.2-0.6', 'bpQ_0.6-1.0', 'bpQ_1.0-1.5', 'bpQ_1.5-2.0', 'bpQ_2.0-3.0', ...
    'fpkE', 'heightE', 'zetaE', 'fpkQ', 'heightQ', ...
    'fAR', 'zetaAR', ...
    'gainR_0.1-0.4', 'gainR_0.4-0.8', 'gainR_0.8-1.5', ...
    'phaseR_0.1-0.4', 'phaseR_0.4-0.8', 'phaseR_0.8-1.5', ...
    'ssGain', 'ayRatio', 'oppSteer', ...
    'Vstraight', 'gainS_r', 'phaseS_r', 'gainS_ay', 'phaseS_ay', 'bpS_1.0-2.0', 'fpkS', 'heightS'};
end
