% EXPORT_PI_TEST_VECTORS  Reference run for the Python plant parity test (P10).
%   One full run with disturbance and a parameter step, written to pi/test_vectors/plant_run.mat.
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);
p0 = change_detector.nominalParams();
pA = change_detector.applyScenario(p0, struct('addedMassKg', 1500, 'mountXM', -1.2, 'kf', 0.8));
prof = change_detector.makeManeuverProfile(struct(), 3);
dist = change_detector.makeDisturbance(prof.t, struct(), 1003);
sched = struct('tStart', 100, 'tEnd', 100);
out = change_detector.simulatePlant(prof, dist, p0, pA, sched);

vec = @(p) [p.m p.lf p.lr p.Izz p.Caf p.Car p.sigmaF];
sampleRateHz = 100;
timestampS = prof.t(:);
sequence = (0:numel(timestampS)-1)';
edge = struct('timestamp_s', timestampS, 'sequence', sequence, ...
    'delta', prof.delta(:), 'Vx', prof.Vx(:), 'r', out.r(:));
diagnostics = struct('ay', out.ay(:), 'ydot', out.ydot(:), ...
    'alphaF', out.alphaF(:), 'X', out.X(:), 'Y', out.Y(:), 'psi', out.psi(:), ...
    'params', out.params);
assert(all(isfinite([edge.delta; edge.Vx; edge.r; edge.timestamp_s])));
assert(all(diff(edge.timestamp_s) == 0.01));
assert(isequal(edge.sequence(:), (0:numel(edge.sequence)-1)'));
ref = struct('schema_version', 1, 'units_version', 1, 'feature_version', 1, ...
    'model_version', 0, 'sample_rate_hz', sampleRateHz, ...
    'sample_period_s', 1/sampleRateHz, 'channel_order', {{'delta', 'Vx', 'r'}}, ...
    'timestamp_origin', 'stream_start', 'source', 'matlab_plant', ...
    'seed', 3, 'edge', edge, 'diagnostics', diagnostics, ...
    't', prof.t, 'delta', prof.delta, 'Vx', prof.Vx, 'Fyd', dist.Fyd, 'Mzd', dist.Mzd, ...
    'p0', vec(p0), 'p1', vec(pA), 'tStart', sched.tStart, 'tEnd', sched.tEnd, 'imuX', p0.imuXFromRearAxleM, ...
    'r', out.r, 'ay', out.ay, 'ydot', out.ydot, 'alphaF', out.alphaF, 'X', out.X, 'Y', out.Y, 'psi', out.psi, ...
    'params', out.params); %#ok<NASGU>
folder = fullfile(projectRoot, 'pi', 'test_vectors');
if ~isfolder(folder), mkdir(folder); end
save(fullfile(folder, 'plant_run.mat'), '-struct', 'ref', '-v7');
fprintf('wrote %s (%d samples)\n', fullfile(folder, 'plant_run.mat'), numel(prof.t));
